synopsis:     "Coq XHL Library"
description:  "Coq XHL Library"
name:         "coq-xhl"
version:      "0.1"
opam-version: "2.0"
maintainer:   "pierre-yves@strub.nu"
authors:      "Pierre-Yves Strub"
homepage:     "https://github.com/strub/xhl"
bug-reports:  "https://github.com/strub/xhl/issues"
dev-repo:     "git+https://github.com/strub/xhl"
license:      "CECILL-B"

depends: [
  "rocq-core"                    { (>= "9.0" & < "9.2~") }
  "dune"
  "rocq-mathcomp-algebra"   { >= "2.4" }
  "rocq-mathcomp-classical" { = "dev" }
  "rocq-mathcomp-analysis" { = "dev" }
  "rocq-mathcomp-reals" { = "dev" }
  "rocq-mathcomp-experimental-reals" { = "dev" }
  "rocq-mathcomp-ssreflect" { >= "2.4" }
]

pin-depends: [
  [ "rocq-mathcomp-classical.dev"          "git+https://github.com/lyonel2017/analysis.git#feature-esum-psum" ]
  [ "rocq-mathcomp-reals.dev"              "git+https://github.com/lyonel2017/analysis.git#feature-esum-psum" ]
  [ "rocq-mathcomp-reals-stdlib.dev"       "git+https://github.com/lyonel2017/analysis.git#feature-esum-psum" ]
  [ "rocq-mathcomp-analysis.dev"           "git+https://github.com/lyonel2017/analysis.git#feature-esum-psum" ]
  [ "rocq-mathcomp-analysis-stdlib.dev"    "git+https://github.com/lyonel2017/analysis.git#feature-esum-psum" ]
  [ "rocq-mathcomp-experimental-reals.dev" "git+https://github.com/lyonel2017/analysis.git#feature-esum-psum" ]
]

build: [ "dune" "build" "-p" name "-j" jobs ]
