synopsis:     "Coq XHL Library"
description:  "Coq XHL Library"
name:         "coq-xhl"
version:      "0.1"
opam-version: "2.0"
maintainer:   "pierre-yves@strub.nu"
authors:      "Pierre-Yves Strub"
homepage:     "https://github.com/strub/xhl"
bug-reports:  "https://github.com/strub/xhl/issues"
dev-repo:     "git+https://github.com/strub/xhl"
license:      "CECILL-B"

depends: [
  "coq"                    { >= "9.0"   }
  "dune"
  "coq-mathcomp-algebra"   { >= "2.4" }
  "coq-mathcomp-classical" { >= "1.13" }
  "coq-mathcomp-experimental-reals" { >= "1.13" }
  "coq-mathcomp-ssreflect" { >= "2.4" }
]

build: [ "dune" "build" "-p" name "-j" jobs ]
